export type Study = {
  id: number
  pub_db: string | null
  pub_code: string | null
  pub_doi: string | null
  pub_year: number | null
  pub_authors: string | null
  pub_title: string | null
  pub_journal: string | null
  ci_ordo_term: string | null
  ci_ordo_code: string | null
  ci_omim_term: string | null
  ci_omim_code: string | null
  ci_type: string | null
  ci_grade: string | null
  ci_ocelm: number | null
  ci_n: number | null
  ci_desc: string | null
  grm_reference: string | null
  grm_hgnc_symbol: string | null
  grm_transcript: string | null
  grm_entrez_gene_id: string | null
  grm_ensemble_gene_id: string | null
  grm_ensemble_transcript_id: string | null
  grm_chrm: string | null
  grm_37_start: number | null
  grm_37_end: number | null
  grm_38_start: number | null
  grm_38_end: number | null
  grm_cdna: string | null
  grm_protein: string | null
  grm_var_type: string | null
  grm_rnda_tag: string | null
  grm_37_pos: number | null
  grm_38_pos: number | null
  grm_inheritance_code: string | null
  grm_inheritance_term: string | null
  trt_db: string | null
  trt_term: string | null
  trt_code: string | null
  trt_cl_eff: string | null
  trt_bio_eff: string | null
  trt_negative: string | null
  trt_comments: string | null
}